### ISSUE TITLE
Cache missing some repositories sometimes 

### ISSUE THREAD

**Issue by fjahr** [rpki-client/rpki-client-portable#116]
I regularly run `rpki-client -d /temp/path` because I am building mappings between prefixes and ASNs with the results in the temp path. I am sometimes seeing whole repositories are missing from the cache folder. For example, yesterday I ran and had `rpki.arin.net`, `rpki.miralium.net`, `rpki.sailx.co`, `ca.nat.moe` and `rpki.tools.westconnect.ca` in the cache and then today when I ran again all of them were missing.

I would like to understand what is causing this and how I could get a more consistent result. Is this more likely to be an issue on the repository side (maintenance etc.) or is it more likely to be something with my connection? Is there a strategy that could make this more reliable?

The only difference in the way I ran `rpki-client` was the date and time of day.

**Comment by job** [comment]
We would need the log files to understand what happened.

What operating system is this? Why not use the default paths? It seems your application of `rpki-client` (mapping prefixes to ASNs) doesn't need a temporary directory.

The `-d` directory is intended to be a stable backend to help survive across repository maintenances and connection issues; so if there are reliability issues with that directory (for example, multiple concurrent processes scribbling in the same directory) then things will go bad

**Comment by job** [comment]
you can capture logs like so:

`rpki-client -v 2>&1 | ts  | tee logfile.log`

**Comment by fjahr** [comment]
> you can capture logs like so:

Thanks, I realized that the logs would be helpful a bit too late and I can't recover them now. We need to add better logging into our project so the logs are captured in a dedicated file and can be inspected later.

> What operating system is this? Why not use the default paths? It seems your application of rpki-client (mapping prefixes to ASNs) doesn't need a temporary directory.

This was macos running a nix shell. We are using dedicated path mainly for debugging and to make it possible to share the data later if we get inconsistent results since we try to make the process as transparent and reproducible as possible. When we run we make note of the timestamp and save all the files in a dedicated folder. That allows us to get a consistent result even when re-running the process again days later on the same folder and by passing the -P flag with the timestamp. We also sometimes run the process as a group so that multiple users (hopefully) get the same result when starting at the exact same time. Here the timestamp also helps get a consistent result because this decouples the expiry of ROAs from the download and verification speed of each users machine. You can see an example of this here: https://github.com/fjahr/asmap-data/issues/15.

It occurs to me now that we could use the default path and then copy the files. But I think pre-syncing so the cache is warm even though it's in a separate path should have a similar effect. I will look into that.

**Comment by fjahr** [comment]
I am closing this for now and will reopen when I see this again and have some logs to share.
