### ISSUE TITLE
Releases/Tags etc.

### ISSUE THREAD

**Issue by fjahr** [rpki-client/rpki-client-portable#117]
Following the repo for a while now I am curious if there is a strategy behind what versions get to become a release or just a tag?

Currently on [releases](https://github.com/rpki-client/rpki-client-portable/releases) the latest version is 9.1. On [Tags](https://github.com/rpki-client/rpki-client-portable/tags) the latest is 9.2. Looking at master and the release table 9.3 is out.

I don't want to complain, I am just genuinely curious if there is something I don't see and also I would like to have a bot that tells me when a new version comes out reliably so that I know when to update our dependencies. I had set something up a few months ago but that was checking the releases and so obviously that didn't work reliably lately.

**Comment by botovq** [comment]
There is no strategy. We don't use github for development nor do we really use these repositories for it. Therefore maintenance is not a priority and comes mostly as an afterthought. We can make an effort to try and improve this, but I don't want to make guarantees. Tagging and uploading release assets to github are additional steps and don't really help.

In other words, GitHub should be treated like all other social networks: information available here is unreliable, incomplete and pops up at random. People can live very well without it and also without missing out:

Releases are announced on the announce@openbsd.org [mailing list][1]. The [homepage][2] is kept up-to-date. The release assets are uploaded to the [frp.openbsd.org][3]. Hopefully one of these lends itself to bottification.

That said, I have tagged 9.3 and uploaded releases 9.2 and 9.3.

[1]: https://www.openbsd.org/mail.html
[2]: https://rpki-client.org/
[3]: https://ftp.openbsd.org/pub/OpenBSD/rpki-client/
