### ISSUE TITLE
Nightly GitHub Action failure: 1 out of 2 hunks FAILED -- saving rejects to file imsg.c.rej

### ISSUE THREAD

**Issue by robert-scheck** [rpki-client/rpki-client-portable#118]
Our nightly GitHub Action for the container image [fails](https://github.com/rpki-client/rpki-client-container/actions/runs/11983725329/job/33420584214#step:8:717) since today with:

> ```
> 16.11 + ./autogen.sh
> 16.12 pulling upstream openbsd source
> 16.13 copying tal and constraints
> 16.13 copying includes
> 16.30 1 out of 2 hunks FAILED -- saving rejects to file imsg.c.rej
> ```

**Comment by botovq** [comment]
Thanks, sorry for the breakage. The reason for this is some major surgery in the upstream imsg code (used for communication between privsep processes) and on top of the obvious need for regenerating some patches, we'll need to figure out some portability issues. We'll get to it when we can. (Same goes for https://github.com/openbgpd-portable/openbgpd-portable/issues/88).
