### ISSUE TITLE
COPYING and LICENSE file

### ISSUE THREAD

**Issue by robert-scheck** [rpki-client/rpki-client-portable#13]
Is there a specific reason that `COPYING` _and_ `LICENSE` file (with same content) are in Git? Isn't a single `COPYING` like in the 6.6p2 release enough?

**Comment by cjeker** [comment]
Seems to be a left-over from merge with the portable framework of openbgpd.
@sebastianbenoit you ok with removing LICENSE?

**Comment by sebastianbenoit** [comment]
Hi, i removed COPYING and left LICENSE, as discussed with claudio.
