### ISSUE TITLE
Implicit declaration of function 'warnc'

### ISSUE THREAD

**Issue by robert-scheck** [rpki-client/rpki-client-portable#15]
Commit [fbc33757884fada818c04cd542123c809f867a52](https://github.com/rpki-client/rpki-client-openbsd/commit/fbc33757884fada818c04cd542123c809f867a52) leads to a build failure here:

```
main.c: In function 'repo_cleanup':
main.c:1471:5: error: implicit declaration of function 'warnc' [-Werror=implicit-function-declaration]
     warnc(e->fts_errno, "fts_read %s", e->fts_path);
```

**Comment by cjeker** [comment]
Guess this should be replaced with a warnx using strerror.

**Comment by cjeker** [comment]
I committed a change to use warnx + strerror into OpenBSD. Tomorrow this should be available in the rpki-client-openbsd repo.

**Comment by cjeker** [comment]
Checked with Travis CI, this should be fixed now.
