### ISSUE TITLE
rpki-client doesn't tell its version

### ISSUE THREAD

**Issue by robert-scheck** [rpki-client/rpki-client-portable#28]
From what I can see so far, `rpki-client` never tells its version. I wonder if it makes sense to enhance the portable version with some version information output, e.g. `rpki-client -V`, which we're anyway passing in via build-time options such as `-DPACKAGE_VERSION=\"6.8p1\"` already. Oh and yes, there are package managers, but some people build rpki-client on their own from source.

**Comment by job** [comment]
@ggm-at-apnic also suggested the lack of a version string makes things harder for them.

**Comment by cjeker** [comment]
Fixed with 0a2f2d0fd1ded25a0ee5349234ba2e1379205030
There is now a -V option for this:
```
# rpki-client -V
rpki-client: version: 6.8p0
```
