### ISSUE TITLE
Introduction of --with-libtls etc.

### ISSUE THREAD

**Issue by robert-scheck** [rpki-client/rpki-client-portable#38]
When crafting https://github.com/rpki-client/rpki-client-container/commit/99690d30d8aa99457f3caa58758445255feffe20, I had to learn that Alpine's libtls-standalone-dev package doesn't put `tls.h` onto a standard path. Thus I would like to raise the idea for `--with-libtls` etc., that – like for OpenSSL – a `pkg-config` pkg-name (or other individual build-time paths) can be passed, too.

**Comment by cjeker** [comment]
Please check out 0fd7b2b4d7f00d0b730d3fe640827d1e475391da, this should implement what you want.

**Comment by robert-scheck** [comment]
Yes, mostly, but with `--with-libtls=libtls-standalone` on Arch Linux, I somehow get this:

```
checking tls.h usability... yes
checking tls.h presence... no
checking for tls.h... yes
configure: WARNING: tls.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: tls.h: proceeding with the compiler's result
checking for library containing tls_read... -ltls-standalone
checking for tls_default_ca_cert_file... yes
checking for tls_config_set_ca_mem... yes
```

**Comment by cjeker** [comment]
Merged
