### ISSUE TITLE
MacOS 11.2.3 run-time error

### ISSUE THREAD

**Issue by okoeroo** [rpki-client/rpki-client-portable#42]
I'm trying to build and run on Big Sur and get the following error:
```
$ /usr/local/sbin/rpki-client
rpki-client: tls_load_file: No such file or directory
rpki-client: poll[2]: hangup
```

To reproduce:
```
brew install libressl
export LDFLAGS="-L/usr/local/opt/libressl/lib"
export CPPFLAGS="-I/usr/local/opt/libressl/include"
./autogen.sh
./configure
make
make install
/usr/local/sbin/rpki-client
rpki-client: tls_load_file: No such file or directory
rpki-client: poll[2]: hangup
```

**Comment by cjeker** [comment]
Most probably this is failing to load the default cert.pem file. Not sure how this is configured on MacOS X.
Could be /etc/ssl/cert.pem or /usr/local/etc/ssl/cert.pem.

**Comment by cjeker** [comment]
This works for me but I'm stuck on 10.13.6.
I installed libressl via brew.

**Comment by cjeker** [comment]
I committed a better error reporting upstream so you should now see which file it fails to load.

**Comment by cjeker** [comment]
Could you please test with the latest version?
It seems that it works for other people and I can also not reproduce your issue.

**Comment by okoeroo** [comment]
Yes, will check later today.

Op vr 16 apr. 2021 08:33 schreef Claudio Jeker ***@***.***>:

**Comment by cjeker** [comment]
Any news? Does it work now?

**Comment by okoeroo** [comment]
sorry for the delay. Yes! it compiles fully on 11.3.1, but I'm not sure why the output fails. I have this error for example:

rpki-client: ta/ripe: pulling from https://rpki.ripe.net/ta/ripe-ncc-ta.cer
rpki-client: https://rpki.ripe.net/ta/ripe-ncc-ta.cer: TLS connect: ssl verify memory setup failure

**Comment by okoeroo** [comment]
the cache is loaded with files, but  the output directory is not populated.
