### ISSUE TITLE
-r poll loop on debian/redhat?

### ISSUE THREAD

**Issue by job** [rpki-client/rpki-client-portable#46]
environment: debian bullseye, linux 5.9.0

`./build_libtls.sh` was run successfully before building rpki-client-portable

the thing hangs here:

```
$ sudo ./src/rpki-client -r -t /etc/tals/afrinic.tal  -v
rpki-client: ta/afrinic: pulling from https://rpki.afrinic.net/repository/AfriNIC.cer
rpki-client: ta/afrinic: loaded from network
rpki-client: https://rrdp.afrinic.net/notification.xml: pulling from network
^C
```

it appears it is stuck in some kind of `poll()` related loop, strace shows

```
[pid 2171457] poll([{fd=5, events=POLLIN}, {fd=6, events=POLLIN}], 2, -1) = 1 ([{fd=6, revents=POLLHUP}])
[pid 2171457] poll([{fd=5, events=POLLIN}, {fd=6, events=POLLIN}], 2, -1) = 1 ([{fd=6, revents=POLLHUP}])
[pid 2171457] poll([{fd=5, events=POLLIN}, {fd=6, events=POLLIN}], 2, -1) = 1 ([{fd=6, revents=POLLHUP}])
[pid 2171457] poll([{fd=5, events=POLLIN}, {fd=6, events=POLLIN}], 2, -1) = 1 ([{fd=6, revents=POLLHUP}])
```

@robert-scheck saw the same on red hat / fedora

**Comment by cjeker** [comment]
Just as a note for others, build_libtls.sh should only be used by the CI system.

This feels related to issue #45

**Comment by job** [comment]
proposed patch: https://marc.info/?l=openbsd-tech&m=161847743724336&w=2

**Comment by cjeker** [comment]
Should be fixed now.

**Comment by robert-scheck** [comment]
Works for me (RHEL/CentOS, Fedora) with latest commits 927f4a597d25c244e292570c6edd65064425507e and https://github.com/rpki-client/rpki-client-openbsd/commit/fa65aeee7c1343b863e2f7f422e93c339a056648.
