### ISSUE TITLE
build: configure vs autogen.sh

### ISSUE THREAD

**Issue by reschke** [rpki-client/rpki-client-portable#50]
The instructions in README.md say:

> Building
> 
> $ ./configure
> $ make

but "configure" is neither in git nor in the release tar file (tried: https://github.com/rpki-client/rpki-client-portable/archive/refs/tags/7.1.tar.gz)

**Comment by job** [comment]
Ah, the release tarball is https://cdn.openbsd.org/pub/OpenBSD/rpki-client/rpki-client-7.1.tar.gz 

We might need to look into disabling the 'github generated tarball' as that is not a PGP/Signify signed release artefact (and apparently incomplete)

**Comment by reschke** [comment]
Indeed, thanks!

**Comment by robert-scheck** [comment]
> We might need to look into disabling the 'github generated tarball' as that is not a PGP/Signify signed release artefact (and apparently incomplete)

We could try to upload the official release tarball plus signatures using the GitHub API additionally, I guess (not sure if we can disable at GitHub the ability to grab a .tar.gz or .zip from a tag, commit, branch etc.).

**Comment by cjeker** [comment]
Instead of adding more to github I think we should point users to rpki-client.org and the official releases.
This is just a meta-repository that allows us to create the portable releases. It is primarily useful for us maintainers. If you want to install rpki-client on a system you should use the official tarballs instead.

**Comment by job** [comment]
I guess the confusion stems from our git tags carrying names similar to what a tarball filename would be, and tarballs are of course generated from tags as a convenience service. Unsure how to clarify this...

**Comment by job** [comment]
Suggestions welcome, this probably is a documentation issue https://github.com/rpki-client/rpki-client-portable/commit/2190b0b594a9917476b80c4f4b1ec9a2c6359a5b

**Comment by cjeker** [comment]
Is it possible to have github show the INSTALL file instead of README.md? In that case it would be possible to better explain how to use this repository.

**Comment by cjeker** [comment]
Adjusted the documentation a bit more.
