### ISSUE TITLE
Use landlock on linux 5.13 and higher

### ISSUE THREAD

**Issue by job** [rpki-client/rpki-client-portable#51]
Leaving a reminder that perhaps https://landlock.io/ can be used as `unveil()` replacement on Linux systems

**Comment by cjeker** [comment]
See #70

Landlock is no where as usable as I would like. Calling it a replacement for unveil() or pledge() is about the same as calling a rusty saw a replacement to a scalpel. It may work for some medical procedures but heck it makes a big mess.

**Comment by cjeker** [comment]
Actually since the introduction of unveil(2) in the main process landlock no longer works.
ABI 1 is just not capable, ABI 2 seems to be unobtanium right now.

**Comment by cjeker** [comment]
OK, I just committed a workaround for this insanity.
Landlock with ABI 1 must be disabled in the master process.
Landlock with ABI 2 can be used but requires a 5.19 or better 6.X kernel.

We can now consider to merge this into mainline and give some Linux users a little bit more security.

**Comment by cjeker** [comment]
Now landlock is not perfect but it is at least something. We decided to merge #70 since it does increase the security of the parser process and that is at least something.
