### ISSUE TITLE
rpki-client 7.3 fails on Alpine 3.14 with "poll[2]: bad fd"

### ISSUE THREAD

**Issue by robert-scheck** [rpki-client/rpki-client-portable#54]
I end up like this on Alpine 3.14 using the rpki-client 7.3 release (but it works e.g. at Fedora 34):

```
/ # rpki-client -vvv
rpki-client: ta/apnic: pulling from https://rpki.apnic.net/repository/apnic-rpki-root-iana-origin.cer
rpki-client: ta/afrinic: pulling from https://rpki.afrinic.net/repository/AfriNIC.cer
rpki-client: ta/lacnic: pulling from https://rrdp.lacnic.net/ta/rta-lacnic-rpki.cer
rpki-client: ta/ripe: pulling from https://rpki.ripe.net/ta/ripe-ncc-ta.cer
rpki-client: poll[2]: bad fd
/ # rpki-client -V
rpki-client-portable 7.3
/ # 
```

P.S.: The 7.2 release works fine on Alpine 3.14.

**Comment by cjeker** [comment]
On Thu, Sep 23, 2021 at 05:09:46PM -0700, Robert Scheck wrote:
> I end up like this on Alpine 3.14 using the rpki-client 7.3 release (but it works e.g. at Fedora 34):
> 
> ```
> / # rpki-client -vvv
> rpki-client: ta/apnic: pulling from https://rpki.apnic.net/repository/apnic-rpki-root-iana-origin.cer
> rpki-client: ta/afrinic: pulling from https://rpki.afrinic.net/repository/AfriNIC.cer
> rpki-client: ta/lacnic: pulling from https://rrdp.lacnic.net/ta/rta-lacnic-rpki.cer
> rpki-client: ta/ripe: pulling from https://rpki.ripe.net/ta/ripe-ncc-ta.cer
> rpki-client: poll[2]: bad fd
> / # rpki-client -V
> rpki-client-portable 7.3
> / # 
> ```
> 

Most probably a build issue where openssl and libressl libraries and
includes are mixed up.

-- 
:wq Claudio

**Comment by robert-scheck** [comment]
> Most probably a build issue where openssl and libressl libraries and includes are mixed up.

Thank you very much for the pointer! While LibreTLS from Alpine Edge was required at a certain point in time, it is meanwhile no longer, so @job fixed it via https://github.com/rpki-client/rpki-client-container/commit/1af91a79a705ef72630614d9193ef943900a8237.
