### ISSUE TITLE
Debug Run Failure

### ISSUE THREAD

**Issue by pmawsonau** [rpki-client/rpki-client-portable#57]
rpki-client is failing to complete a run, this stopped for us approx 1 week ago on one machine (but find on another), the app just hangs and fails to provide any output when it gets to the end.  The JSON file does not get created.  Is there a debug mode to work out where this is failing?

 rpki-client -j
The RIPE NCC Certification Repository is subject to Terms and Conditions
See http://www.ripe.net/lir-services/ncc/legal/certification/repository-tc

rsync: failed to connect to rpki.admin.freerangecloud.com (172.98.192.101): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]
rpki-client: rsync rsync://rpki.admin.freerangecloud.com/repo failed
rpki-client: rpki.admin.freerangecloud.com/repo/FRC-CA/2/5D35939557110CC43429AE301F7CEF0E5889942B.mft: No such file or directory
The RIPE NCC Certification Repository is subject to Terms and Conditions
See http://www.ripe.net/lir-services/ncc/legal/certification/repository-tc

rpki-client: rpki-repository.nic.ad.jp/ap/A91A73810000/699/bkqeJzVTPVpOXDMPDUQnaPOy7iw.roa: RFC 3779 resource not subset of parent's resources
rpki-client: rpki.afrinic.net/repository/member_repository/F3646C24/1C86B7862B5B11EC8EBEF540D8A014CE/_r9_454NpaYN1sjcZoHO9aJGKC4.mft: No such file or directory
rpki-client: rpki.afrinic.net/repository/member_repository/F362C7E9/08F07C14E8D911E98515C740F8AEA228/8A9DED60330411ECB9F7B454D8A014CE.roa: certificate is not yet valid

rsync: failed to connect to krill.openx.com.br (177.91.162.90): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]
rpki-client: rsync rsync://krill.openx.com.br/repo failed
rpki-client: rpki.admin.freerangecloud.com/repo/FRC-CA/7/FA048AF3EA62E5575B4698C5CC2403982893F0C5.mft: No such file or directory
rpki-client: rpki.admin.freerangecloud.com/repo/FRC-CA/3/A0DF8EB28D12F9CDF7A68B3DC7A56576748B2E54.mft: No such file or directory
rpki-client: rpki.admin.freerangecloud.com/repo/FRC-CA/6/75E8A027E92C15B9414A59AC096BD4634B906914.mft: No such file or directory
rpki-client: rpki.admin.freerangecloud.com/repo/FRC-CA/0/C8935FDCA5028AE8209FEC82AD8AE8CFB7C6E776.mft: No such file or directory
rpki-client: krill-eval-ctec.charter.com/repo/Charter_CTEC_Lab/3/47CA36B68F7EBB87A8E744A7072F9E3D860263A1.mft: mft expired on Jun 19 16:26:00 2021 GMT
rpki-client: rpki-repo.registro.br/repo/HX3z3YpiLS9QubGAVEqGBhb1VVpkZCsgxGknQcP2wpSt/0/7D8A9531076B1611BA99C6F0DE67D1C23D9D4D69.mft: mft expired on Oct 27 23:50:00 2021 GMT
rpki-client: rpki-repo.registro.br/repo/2o4paBoq6LzvHAs31rV7xtet2Hzi7TKLjBWpoMv7wDcQ/0/3BE7834F5C952166B2344224A6CDC53A4B6CBC5D.mft: mft expired on Oct 29 12:10:00 2021 GMT
rpki-client: krill.openx.com.br/repo/openx/0/903DCC9CE00A3A63C8A767354675DE030AAD480F.mft: No such file or directory
rpki-client: rpki-repo.registro.br/repo/681Sn9wiCnn8ANQrJM6gRLGiMQoRQdk5kUbodfdYqyGS/0/24CE2A1D7D0C33062228DAC12389B9C1E0BF7321.mft: mft expired on Oct 29 12:40:00 2021 GMT
rpki-client: rpki-repo.registro.br/repo/7YS5o7RPbEdQ5uu7j5JTH3NNkdaeanEfgpMK2MEe7YZ5/0/EDCE71D4C0B931EADD49D9EE3F380B39FC716C3C.mft: mft expired on Oct 29 12:20:00 2021 GMT
rpki-client: rpki-repo.registro.br/repo/C6CpBe3iBpA78BroqAnRfz5gEWpz76nR9fuVbQGBDRxP/0/78B729D22DCEFB9255CD272064BD0C7255672C12.mft: mft expired on Oct 30 17:36:00 2021 GMT
rpki-client: rpki-repo.registro.br/repo/WMHJfnYE8NUC9RUbAsx363tYt5U4gN6UpB6umWUffbG/0/4A00AF1325B5DBF0EA04C441E5B9FB9ABD85F2C1.mft: mft expired on Oct 28 00:50:56 2021 GMT
rpki-client: rpki-ca.uepg.br/repo/uepg_ca/0/279CDDC78D1BDE4B86DFC07FC751BB7A9FD53CEC.mft: No such file or directory

rpki-client: rpki1.terratransit.de/repo/TerraTransit/79/EF6D5C4FF0D822C54B3BB2000663091CBC4F41E6.mft: No such file or directory
rpki-client: rpki1.terratransit.de/repo/TerraTransit/87/07B1A2CB9D13D3AE494D675F20F04AC17F7F5DCB.mft: No such file or directory
rpki-client: rpkica.mckay.com/rpki/MCnet/UEh2SAvdIgPsUFdv92RSSaNqBnY.mft: No such file or directory
rpki-client: rpki.admin.freerangecloud.com/repo/FRC-CA/5/7EA5316DBDAC01CD05D0EAA05A89C04DA3E7398F.mft: No such file or directory
rpki-client: r.magellan.ipxo.com/repo/3df3b03a-ee5f-4212-bbe8-239ad294f50e-589fc7fbb6-1/0/C486E45F80D7067C26D7C927E756CE4EA826B006.mft: mft expired on Oct 28 17:10:00 2021 GMT

rpki-client: ca.rg.net/rpki/RGnet-OU/ovsCA/IOUcOeBGM_Tb4dwfvswY4bnNZYY.mft: No such file or directory
rsync: failed to connect to cc.rg.net (147.28.0.47): Connection timed out (110)
rsync: failed to connect to cc.rg.net (2001:418:1::47): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]
rpki-client: rsync rsync://cc.rg.net/rpki failed
rpki-client: cc.rg.net/rpki/RGnet-cc/gY5eZDw9ohLSAi1mlxSwh1gVFcY.mft: No such file or directory

Centos 8.1
rpki-client 7.2

**Comment by cjeker** [comment]
Could you retest this with a current version 7.4 was just release but I think even 7.3 may be good enough.
I remember fixing errors like this some time ago. I guess your run aborts after hitting the runtime timeout after 1 hour, right? The error should be "excessive runtime (3600 seconds), giving up".

**Comment by robert-scheck** [comment]
If you are using the rpki-client-7.2-1.el8 RPM package from EPEL currently, [rpki-client-7.4-1.el8](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2021-51a1d774bf) reached the EPEL 8 testing repository just a couple of hours ago.

**Comment by pmawsonau** [comment]
Will upgrade to 7.4.  Closing off.
