### ISSUE TITLE
document steps to obtain "LibreSSL libtls" on Ubuntu

### ISSUE THREAD

**Issue by reschke** [rpki-client/rpki-client-portable#58]
...because it doesn't seem to be as simple as it should be :-).

**Comment by reschke** [comment]
ok - found https://github.com/rpki-client/rpki-client-portable/blob/master/build_libtls.sh

**Comment by cjeker** [comment]
You should not use that. This is only for the CI system there is no warranty that this will not eat your system.

**Comment by cjeker** [comment]
there is libretls and there are libretls packages for e.g. debian available. Push ubuntu to pull that package into their packaging system.

**Comment by reschke** [comment]
The plan is to use it in a docker image with the sole purpose of building rpki-client.

**Comment by cjeker** [comment]
why don't you use https://github.com/rpki-client/rpki-client-container?

**Comment by reschke** [comment]
Because company policy requires a specific base Ubuntu image for everything.

**Comment by cjeker** [comment]
Ubuntu 22.04 should have a package for libtls (libtls22 and libtls-dev).
I have no Ubuntu install to try this on but I guess it will just work.
