### ISSUE TITLE
Expose metadata as OpenMetrics

### ISSUE THREAD

**Issue by momorientes** [rpki-client/rpki-client-portable#61]
As discussed with @job and @robert-scheck on IRC I would appreciate to see the `metadata`-dict in the `vrps.json` exposed in the [OpenMetrics](https://datatracker.ietf.org/doc/html/draft-richih-opsawg-openmetrics-00) format.

An example output could be:
```
# HELP rpki_client_roas_count Total number of ROAs
# TYPE rpki_client_roas_count gauge
rpki_client_roas_count 100020

[...]
```

[OpenMetrics requires the software to natively answer to HTTP GET](https://datatracker.ietf.org/doc/html/draft-richih-opsawg-openmetrics-00#section-2)  which I suppose is a no-go for `rpki-client`, however prometheus users would still be able to ingest the data either via a webserver or by utilizing the [textfile collector of node_exporter](https://github.com/prometheus/node_exporter#textfile-collector).

If this in general is relevant to `rpki-client` I'll happily help with the OpenMetrics side, I sadly can't contribute any C-Code though.

**Comment by cjeker** [comment]
This is currently not a priority for us but it is on the todo list.
Happy if someone else writes an output module for this (it should not be part of the JSON output but an own file instead).

**Comment by cjeker** [comment]
Support to write a metrics file was added a few days ago.
The problem is that the textfile collector of node_exporter is not OpenMetrics compatible. We had to use "gauge" in place of "info" or "stateset" types. But with that hack the file can be served by node_exporter. Another option is to serve it directly from a webserver if one is running. How to serve the metrics is outside the scope of rpki-client.

Happy to get feedback on the collected metrics. Happy to extend or adjust it.

**Comment by robert-scheck** [comment]
What would be needed to integrate this into the rpki-client container image? Just something like a minimal HTTP daemon serving this file via port 9100?

**Comment by cjeker** [comment]
Yes, I think that is a decent solution for the container. Not sure if port 9100 is the right one but lets start with that.

Make sure the Content-Type of the file is `application/openmetrics-text; version=1.0.0; charset=utf-8`

**Comment by rfc1036** [comment]
You can pick a unused port here and register it: https://github.com/prometheus/prometheus/wiki/Default-port-allocations

**Comment by robert-scheck** [comment]
But aren't the port allocations for when you actually write your own exporter (which I would like to avoid)? It does not make sense for me to blow up the tiny container image with yet another Golang exporter implementation (most of them seem to be Golang), especially as the image won't provide multiple exporters anyway. Everybody using the container image can remap the default port individually using `-p 9100:12345` (at Docker/Podman).

**Comment by cjeker** [comment]
@robert-scheck, I agree that the ports can be remapped. I'm just not sure if a default of 9100 is sensible. We could just grab some other random number like 80 instead ;-)

**Comment by robert-scheck** [comment]
https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#iana-considerations-iana says
> The port assigned by IANA for clients exposing data is <9099 requested for historical consistency>.

**Comment by cjeker** [comment]
@robert-scheck do we need to keep this open or did you adjust the rpki-client container image?

**Comment by robert-scheck** [comment]
It didn't land in the container image yet, because reallife kept me quite busy otherwise. I created https://github.com/rpki-client/rpki-client-container/issues/2 so that this one can be closed for now, as it's in rpki-client itself already.
