### ISSUE TITLE
MacOS WimplicitFunctionDeclaration

### ISSUE THREAD

**Issue by stipmonster** [rpki-client/rpki-client-portable#62]
Currently the check at https://github.com/rpki-client/rpki-client-portable/blob/master/configure.ac#L206 trows an WimplicitFunctionDeclaration for the _exit funtion given that it does not include unistd.h. Currently the macports install proccess trows a warning for this. 
I propose changing this check to also include unistd.h For more information see https://trac-test.macports.org/wiki/WimplicitFunctionDeclaration

**Comment by cjeker** [comment]
Thanks for the report. Fixed in 2b9ba5e0c49764de999593a01564f4bb94616e05
I also fixed OpenBGPD-portable and informed the OpenSSH-portable maintainer from where this test is.
