### ISSUE TITLE
Possibly incorrect expiration date?

### ISSUE THREAD

**Issue by 0verloader** [rpki-client/rpki-client-portable#64]
After running rpki-client, I discovered that most ROAs are about to expire in the next 1,2 days.  Actually, the most long-living ROA will expire in six days. Is that actually the case or something is wrong?

**Comment by cjeker** [comment]
These short expire times result from the the short validity of CRL and MFT files. An expire time of 1-2 days is fine when rpki-client is run every hour (which is the suggested poll time). In general it is up to the CAs to set the certificate, mft and crl expire times to sensible values.
