### ISSUE TITLE
outformats patch misaligned

### ISSUE THREAD

**Issue by job** [rpki-client/rpki-client-portable#66]
This [blurp](https://github.com/rpki-client/rpki-client-portable/blob/master/patches/0003-Emit-all-output-formats-on-non-OpenBSD-systems.patch#L19-L22) needs to move up a bit into inside the `if (outputdir != NULL) {` stanza. Right now we are not generating all formats in portable it seems

**Comment by cjeker** [comment]
Should be fixed in 0f802f9c3236527992e97d1422c4cbf7adc23215

**Comment by robert-scheck** [comment]
Confirming [successful run](https://github.com/rpki-client/rpki-client-container/actions/runs/2368879301) with commit https://github.com/rpki-client/rpki-client-portable/commit/0f802f9c3236527992e97d1422c4cbf7adc23215 - thank you.
