### ISSUE TITLE
7.9 - release

### ISSUE THREAD

**Issue by thezoggy** [rpki-client/rpki-client-portable#68]
- release link on website throws 404 ([rpki-client-7.9.txt](https://ftp.openbsd.org/pub/OpenBSD/rpki-client/rpki-client-7.9.txt))

- github changelog has typo saying its 7.6 instead of 7.9 -- sent pull to fix

**Comment by sebastianbenoit** [comment]
Hi, the 404 will be fixed momentarily, there was a permission error causing the txt file not to be synced to the ftp mirrors. The tar.gz was there though.

**Comment by cjeker** [comment]
Updated changelog as well.
