### ISSUE TITLE
Upload signing public key of rpki-client to keys.openpgp.org?

### ISSUE THREAD

**Issue by robert-scheck** [rpki-client/rpki-client-portable#72]
Do you see any chance to upload the public key of RSA key B5B6416FEA6DDA05EA562A9FCB987F2783972FF9, being used for signing rpki-client release tarballs, to keys.openpgp.org? This would allow Fedora to switch from the current binary GnuPG output blob (manually created) to the ASCII format provided there.

**Comment by sebastianbenoit** [comment]
i guess this is done

**Comment by robert-scheck** [comment]
Yes, it works perfectly – I switched to keys.openpgp.org for the Fedora package a few moments ago. Thank you very much!
