### ISSUE TITLE
Geofeed validation doesn't seem to work correctly on Ubuntu 22.04.1 LTS - RPKI-client 8.2 

### ISSUE THREAD

**Issue by ebais** [rpki-client/rpki-client-portable#77]
wget https://sobornost.net/geofeed.csv

rpki-client -f geofeed.csv 
Output : 

File:                     geofeed.csv
Hash identifier:          VOXBRdQpiyALlLRdo3OkLbLIY4PexRlci/0EM9Fc21U=
rpki-client: invalid address: 2001:67c:208c::/48
Validation:

**Comment by botovq** [comment]
Looks like glibc's `inet_net_pton(3)` can't handle IPv6 addresses. We should be using `inet_pton(3)` instead.

**Comment by cjeker** [comment]
I will just fix the configure script to properly probe for AF_INET6 support. Since we already ship our inet_net_pton
