### ISSUE TITLE
GitHub Action failure: undefined reference to `inflate'

### ISSUE THREAD

**Issue by robert-scheck** [rpki-client/rpki-client-portable#90]
My unrelated documentation-only commit 32b8c63bf9be79bf82e60c5a3165e12ac9a6b09f lead to a GitHub Action [failure](https://github.com/rpki-client/rpki-client-portable/actions/runs/5260727058/jobs/9508018624#step:9:671):

> ```
> /usr/bin/ld: rpki_client-http.o: in function `http_handle':
> http.c:(.text+0x13aa): undefined reference to `inflate'
> /usr/bin/ld: http.c:(.text+0x19a6): undefined reference to `inflateReset'
> /usr/bin/ld: http.c:(.text+0x19b8): undefined reference to `inflateEnd'
> /usr/bin/ld: rpki_client-http.o: in function `http_free':
> http.c:(.text+0x1f87): undefined reference to `inflateEnd'
> /usr/bin/ld: rpki_client-http.o: in function `http_read':
> http.c:(.text+0x2a9a): undefined reference to `inflateInit2_'
> /usr/bin/ld: rpki_client-http.o: in function `http_done':
> http.c:(.text+0x4113): undefined reference to `inflateReset'
> /usr/bin/ld: http.c:(.text+0x4125): undefined reference to `inflateEnd'
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```

Looks like zlib is a new dependency and should make it into `configure` etc.?

**Comment by cjeker** [comment]
Fixed in b288c132607996c64705178d27d612c214fb7529
